Portfolio: finish mobile version
RolandAmini/portfolio-mobile pull request #3
Opened 2023-07-08 20:54 UTC by RolandAmini

I have made sure the content of the "About myself" section is aligned with flexbox.

In order to lay out the elements in "Works" section I have used CSS Grid and Flexbox combined. Also Used CSS Grid in the main container that contains all of the cards and used Flexbox to lay out an individual card

2023-07-08 21:53 UTC, souad988 requested changes
Hi @RolandAmini , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


![Uploading 242722065-db428b0c-8dfc-49c4-a156-42f227e32868.gif…]()


## Highlights
Good PR description
Good use of html semantic tags
Professional README

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-08 21:53 UTC, souad988 commented on index.html
> +
Great work was done so far by using semantic tags and descriptive classNames, only some small styling adjustements needed : 

1. the title needs to be bolder and the size needs to be increased
2. the cards horizontal margin needs to be increased to match the given design

![image (14)](https://github.com/RolandAmini/portfolio-mobile/assets/59707859/03e5464a-118c-4b10-b985-910ac2a94609)
![image (15)](https://github.com/RolandAmini/portfolio-mobile/assets/59707859/370c6305-cb03-4c4b-876e-acce531a791b)

2023-07-08 21:53 UTC, souad988 commented on index.html
> +          <button class="btn btn-skill">See Project</button>
![image (20)](https://github.com/RolandAmini/portfolio-mobile/assets/59707859/4e10fa55-c1da-46e3-8dfd-cd2659253b20)
your button are well styled they look exactly like the design but still missing the hover and press effects

2023-07-08 21:53 UTC, souad988 commented on index.html
> +          </ul>
Kindly add the missing image to this card

![image (19)](https://github.com/RolandAmini/portfolio-mobile/assets/59707859/a146ab3f-33e4-41b7-8cdd-c4a7d3c5452f)

2023-07-08 21:53 UTC, souad988 commented on index.html
> +          <button class="btn btn-skill">See Project</button>
your button are well styled they look exactly like the design but still missing the hover and press effects 

![image (20)](https://github.com/RolandAmini/portfolio-mobile/assets/59707859/13e99ca3-a98d-4d91-b56c-798d1f46ff8e)

2023-07-08 21:53 UTC, souad988 commented on index.html
> +</div>
Kindly fix this card styling to match the design

![image (21)](https://github.com/RolandAmini/portfolio-mobile/assets/59707859/61fadc50-b132-4071-add3-187963648f5c)

2023-07-08 21:54 UTC, souad988 requested changes
Hi @RolandAmini , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


![Uploading 242722065-db428b0c-8dfc-49c4-a156-42f227e32868.gif…]()


## Highlights
Good PR description
Good use of html semantic tags
Professional README

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-08 22:46 UTC, RolandAmini commented
thank you I have done all changes

2023-07-08 23:52 UTC, taldr27 approved these changes
# Status: Approved! 🟢 
Hi @RolandAmini, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉

![congrats](https://media.giphy.com/media/3o6fIUZTTDl0IDjbZS/giphy.gif)

## Highlights 🎉 
✅ Professional and customized README. 
✅ Linters tests passing.
✅ Correct use of GitHub Flow.
✅ Incorporates feedback from previous code reviews.
✅ Nice mobile design.

-----
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @taldr27 in your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). <img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="3%"/>_

2023-07-10 07:08 UTC, shella12 approved these changes
Hi @RolandAmini, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Great design implementation ✔️ 
- README is professional 👍 
- Implemented all required changes 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-25 22:36 UTC, merged